### PR TITLE
Recognize existing DJS installations

### LINKED ISSUE #117: Cannot install DJS
Acca 1.0.26

Pressing scheduler button at the main window gives an alert "DJS should be installed".

When pressing "Install" the same alert appears again and again.

In fact DJS functions are not available.

### PR DESCRIPTION
**Pull request by pagdot**
Fixes #117

(Testing it overnight if everything triggers and will remove draft state if everything works)

### CODE REVIEW

**Comment by MatteCarra** [comment]
Thanks a lot!
Let me know if you need any help/info!

**Comment by pagdot** [comment]
Sorry for the delay. I had the issue that the scheduled profiles didn't get enrolled and hadn't really time+motivation to debug.

Since then I debugged it and found out that djs is running (yeah :) ), verified by writing to files on my sd card and checking if djs is able to execute acca, by writing theoutput from `help` in a file. I've tried setting rules on the command line myself without success though...

A few days ago it seems like a djs profile got actually enrolled by chance at the correct time. (I didn't change anything for ~5 days though)

It seems like enrolling profiles from the command line doesn't (always) work. This may be similar to #120 or #125. Setting profiles from the app works though. Does the App overrides profiles or are there further requirements besides being root to change settings?

**Comment by MatteCarra** [comment]
I will try to talk to VR25 and get a working version of djs bundled with acca

**Comment by MatteCarra** [comment]
Djs is now working!

**Pull request closed without merging**
