### PR TITLE
New AccA 1.0.33 (37)

### PR DESCRIPTION
**Pull request by nialone**

### CODE REVIEW

**Comment by MatteCarra** [comment]
Thank you for the contribution!
I will review it tomorrow!

**Comment by nialone** [comment]
No problem. Here's a new build, rename zip in to apk.
p.s.: Bug #167 is still relevant, my phone drops. ) 
[ACCAb2.zip](https://github.com/MatteCarra/AccA/files/6934593/ACCAb2.zip)

**Comment by MatteCarra** [comment]
I have not understood what you said in issue 167. I will try to forward it to acc dev

**Comment by nialone** [comment]
Sorry, this is a machine translation.
I write the [problem](https://github.com/VR-25/acc/issues/107) in the ACC branch.
Thank you.

**Pull request merged**
