### PR TITLE
Profiles, widget, logs, unit of measurements ... in the piggy bank

### PR DESCRIPTION
**Pull request by nialone**
Most importantly, instead of the acc config concept, a profile is used. It contains: acc configuration, scripts, boolean parameters and so on. It can be expanded for the necessary tasks. Also, you can disable any acc configuration parameter in the profile.

If you open the main tab and click on editing the config, then this is not a profile, these are clean acc settings, there are their own switches. The dashboard displays only the current settings in acc.

This must be seen and understood.)

### CODE REVIEW

**Comment by MatteCarra** [comment]
Oh wow, this is huge

**Comment by nialone** [comment]
If in total, yes, it is big.
I rarely click the commit button.
I'm sorry, half of the code is my re-alignment.

Most importantly, instead of the acc config concept, a profile is used. It contains: acc configuration, scripts, boolean parameters and so on. It can be expanded for the necessary tasks. Also, you can disable any acc configuration parameter in the profile.

If you open the main tab and click on editing the config, then this is not a profile, these are clean acc settings, there are their own switches. The dashboard displays only the current settings in acc.

This must be seen and understood.)

**Comment by MatteCarra** [comment]
Is this work in progress or is it ready?

**Comment by nialone** [comment]
It's hard to say, there will always be something to finalize. The main parts are ready. )
I'm worried about the database migration, I hope it works.

**Pull request merged**
